language: ruby
dist: trusty
sudo: required

before_install:
  - sudo apt update
  - sudo apt install g++

before_script:
  - echo $REDDIT_PW > pass
  - echo $REDDIT_SECRET > secret
  - echo $OSU_API_KEY > key
  - cd oppai; ./build.sh; cd ..

after_script:
  - rm pass secret key

rvm:
  - 2.4.0
  - 2.4.1
  - ruby-head
