language: ruby
dist: trusty

before_script:
  - echo $REDDIT_PW > lib/pass
  - echo $REDDIT_SECRET > lib/secret
  - echo $OSU_API_KEY > lib/key
  - cd oppai; ./build.sh; cd ..
  - mkdir logs

rvm:
  - 2.4.0
  - 2.4.1
  - ruby-head
