language: python
dist: xenial
python: 3.7
before_script: pip install -r requirements.txt -r requirements.dev.txt
env:
  - AWS_DEFAULT_REGION=us-east-1
script:
  - pytest
  - mypy osubot test
  - black --check osubot test
notifications:
  email: false
