language: ruby
dist: trusty
sudo: required

before_install:
  - sudo apt update
  - sudo apt install g++

before_script:
  - echo $REDDIT_PW > lib/pass
  - echo $REDDIT_SECRET > lib/secret
  - echo $OSU_API_KEY > lib/key
  - cd oppai; ./build.sh; cd ..
  - mkdir logs

after_script:
  - rm -r oppai/oppai lib/pass lib/secret lib/key logs

rvm:
  - 2.4.0
  - 2.4.1
  - ruby-head
