language: ruby
dist: trusty

before_script:
  - mkdir secrets logs
  - echo $REDDIT_PW > secrets/pass
  - echo $REDDIT_SECRET > secrets/secret
  - echo REDDIT_CLIENT_ID > secrets/client
  - echo $OSU_API_KEY > secrets/key
  - echo $OSUSEARCH_KEY > secrets/search_key
  - cd oppai; ./build.sh; cd ..

after_script:
  - rm -r secrets

rvm:
  - 2.4.0
  - 2.4.1
  - ruby-head
