version: "3"
services:
    monitor:
        build: .
        restart: unless-stopped
        env_file: .env
        command: python /root/bin/monitor.py --auto
    videos:
        build: .
        restart: unless-stopped
        env_file: .env
        command: python /root/bin/video_links.py
    server:
        build: .
        restart: unless-stopped
        env_file: .env
        command: flask run
